/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 101
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  sym_host_key = 3,
  sym_querys_key = 4,
  anon_sym_EQ = 5,
  aux_sym_query_any_token1 = 6,
  sym_headers_key = 7,
  anon_sym_COLON = 8,
  anon_sym_SPACE = 9,
  sym_method_key = 10,
  sym_body_key = 11,
  anon_sym_LBRACE = 12,
  anon_sym_COMMA = 13,
  anon_sym_RBRACE = 14,
  sym_json_bool = 15,
  sym_json_null = 16,
  sym_json_string = 17,
  sym_json_number = 18,
  sym_urlencoded_key = 19,
  sym_urlencoded_val = 20,
  sym_urlencoded_equals = 21,
  sym_urlencoded_amper = 22,
  sym_backend_key = 23,
  sym_backendoptions_key = 24,
  aux_sym_backendoption_token1 = 25,
  sym_config_key = 26,
  sym_config_param = 27,
  sym_value = 28,
  sym_number = 29,
  sym_identifier = 30,
  sym_bool = 31,
  sym_comment = 32,
  sym_program = 33,
  sym_section = 34,
  sym_host = 35,
  sym_query = 36,
  sym_query_key = 37,
  sym_query_val = 38,
  sym_query_any = 39,
  sym_query_key_val = 40,
  sym_headers = 41,
  sym_header_key = 42,
  sym_header_val = 43,
  sym_header_key_val = 44,
  sym_method = 45,
  sym_body = 46,
  sym_json_body = 47,
  sym_json_object = 48,
  sym_json_array = 49,
  sym_json_pair = 50,
  sym_json_value = 51,
  sym_urlencoded_body = 52,
  sym_urlencoded_key_val = 53,
  sym_backend = 54,
  sym_backendoptions = 55,
  sym_backendoption = 56,
  sym_config = 57,
  sym_config_setting = 58,
  sym_config_value = 59,
  aux_sym_program_repeat1 = 60,
  aux_sym_query_repeat1 = 61,
  aux_sym_headers_repeat1 = 62,
  aux_sym_json_object_repeat1 = 63,
  aux_sym_json_array_repeat1 = 64,
  aux_sym_urlencoded_body_repeat1 = 65,
  aux_sym_backendoptions_repeat1 = 66,
  aux_sym_config_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_host_key] = "host_key",
  [sym_querys_key] = "querys_key",
  [anon_sym_EQ] = "=",
  [aux_sym_query_any_token1] = "query_any_token1",
  [sym_headers_key] = "headers_key",
  [anon_sym_COLON] = ":",
  [anon_sym_SPACE] = " ",
  [sym_method_key] = "method_key",
  [sym_body_key] = "body_key",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [sym_json_bool] = "json_bool",
  [sym_json_null] = "json_null",
  [sym_json_string] = "json_string",
  [sym_json_number] = "json_number",
  [sym_urlencoded_key] = "urlencoded_key",
  [sym_urlencoded_val] = "urlencoded_val",
  [sym_urlencoded_equals] = "urlencoded_equals",
  [sym_urlencoded_amper] = "urlencoded_amper",
  [sym_backend_key] = "backend_key",
  [sym_backendoptions_key] = "backendoptions_key",
  [aux_sym_backendoption_token1] = "backendoption_token1",
  [sym_config_key] = "config_key",
  [sym_config_param] = "config_param",
  [sym_value] = "value",
  [sym_number] = "number",
  [sym_identifier] = "identifier",
  [sym_bool] = "bool",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym_section] = "section",
  [sym_host] = "host",
  [sym_query] = "query",
  [sym_query_key] = "query_key",
  [sym_query_val] = "query_val",
  [sym_query_any] = "query_any",
  [sym_query_key_val] = "query_key_val",
  [sym_headers] = "headers",
  [sym_header_key] = "header_key",
  [sym_header_val] = "header_val",
  [sym_header_key_val] = "header_key_val",
  [sym_method] = "method",
  [sym_body] = "body",
  [sym_json_body] = "json_body",
  [sym_json_object] = "json_object",
  [sym_json_array] = "json_array",
  [sym_json_pair] = "json_pair",
  [sym_json_value] = "json_value",
  [sym_urlencoded_body] = "urlencoded_body",
  [sym_urlencoded_key_val] = "urlencoded_key_val",
  [sym_backend] = "backend",
  [sym_backendoptions] = "backendoptions",
  [sym_backendoption] = "backendoption",
  [sym_config] = "config",
  [sym_config_setting] = "config_setting",
  [sym_config_value] = "config_value",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_query_repeat1] = "query_repeat1",
  [aux_sym_headers_repeat1] = "headers_repeat1",
  [aux_sym_json_object_repeat1] = "json_object_repeat1",
  [aux_sym_json_array_repeat1] = "json_array_repeat1",
  [aux_sym_urlencoded_body_repeat1] = "urlencoded_body_repeat1",
  [aux_sym_backendoptions_repeat1] = "backendoptions_repeat1",
  [aux_sym_config_repeat1] = "config_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_host_key] = sym_host_key,
  [sym_querys_key] = sym_querys_key,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_query_any_token1] = aux_sym_query_any_token1,
  [sym_headers_key] = sym_headers_key,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_method_key] = sym_method_key,
  [sym_body_key] = sym_body_key,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_json_bool] = sym_json_bool,
  [sym_json_null] = sym_json_null,
  [sym_json_string] = sym_json_string,
  [sym_json_number] = sym_json_number,
  [sym_urlencoded_key] = sym_urlencoded_key,
  [sym_urlencoded_val] = sym_urlencoded_val,
  [sym_urlencoded_equals] = sym_urlencoded_equals,
  [sym_urlencoded_amper] = sym_urlencoded_amper,
  [sym_backend_key] = sym_backend_key,
  [sym_backendoptions_key] = sym_backendoptions_key,
  [aux_sym_backendoption_token1] = aux_sym_backendoption_token1,
  [sym_config_key] = sym_config_key,
  [sym_config_param] = sym_config_param,
  [sym_value] = sym_value,
  [sym_number] = sym_number,
  [sym_identifier] = sym_identifier,
  [sym_bool] = sym_bool,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym_section] = sym_section,
  [sym_host] = sym_host,
  [sym_query] = sym_query,
  [sym_query_key] = sym_query_key,
  [sym_query_val] = sym_query_val,
  [sym_query_any] = sym_query_any,
  [sym_query_key_val] = sym_query_key_val,
  [sym_headers] = sym_headers,
  [sym_header_key] = sym_header_key,
  [sym_header_val] = sym_header_val,
  [sym_header_key_val] = sym_header_key_val,
  [sym_method] = sym_method,
  [sym_body] = sym_body,
  [sym_json_body] = sym_json_body,
  [sym_json_object] = sym_json_object,
  [sym_json_array] = sym_json_array,
  [sym_json_pair] = sym_json_pair,
  [sym_json_value] = sym_json_value,
  [sym_urlencoded_body] = sym_urlencoded_body,
  [sym_urlencoded_key_val] = sym_urlencoded_key_val,
  [sym_backend] = sym_backend,
  [sym_backendoptions] = sym_backendoptions,
  [sym_backendoption] = sym_backendoption,
  [sym_config] = sym_config,
  [sym_config_setting] = sym_config_setting,
  [sym_config_value] = sym_config_value,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_query_repeat1] = aux_sym_query_repeat1,
  [aux_sym_headers_repeat1] = aux_sym_headers_repeat1,
  [aux_sym_json_object_repeat1] = aux_sym_json_object_repeat1,
  [aux_sym_json_array_repeat1] = aux_sym_json_array_repeat1,
  [aux_sym_urlencoded_body_repeat1] = aux_sym_urlencoded_body_repeat1,
  [aux_sym_backendoptions_repeat1] = aux_sym_backendoptions_repeat1,
  [aux_sym_config_repeat1] = aux_sym_config_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_host_key] = {
    .visible = true,
    .named = true,
  },
  [sym_querys_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_query_any_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_headers_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_method_key] = {
    .visible = true,
    .named = true,
  },
  [sym_body_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_json_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_json_null] = {
    .visible = true,
    .named = true,
  },
  [sym_json_string] = {
    .visible = true,
    .named = true,
  },
  [sym_json_number] = {
    .visible = true,
    .named = true,
  },
  [sym_urlencoded_key] = {
    .visible = true,
    .named = true,
  },
  [sym_urlencoded_val] = {
    .visible = true,
    .named = true,
  },
  [sym_urlencoded_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_urlencoded_amper] = {
    .visible = true,
    .named = true,
  },
  [sym_backend_key] = {
    .visible = true,
    .named = true,
  },
  [sym_backendoptions_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_backendoption_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_config_key] = {
    .visible = true,
    .named = true,
  },
  [sym_config_param] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_host] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym_query_key] = {
    .visible = true,
    .named = true,
  },
  [sym_query_val] = {
    .visible = true,
    .named = true,
  },
  [sym_query_any] = {
    .visible = true,
    .named = true,
  },
  [sym_query_key_val] = {
    .visible = true,
    .named = true,
  },
  [sym_headers] = {
    .visible = true,
    .named = true,
  },
  [sym_header_key] = {
    .visible = true,
    .named = true,
  },
  [sym_header_val] = {
    .visible = true,
    .named = true,
  },
  [sym_header_key_val] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_json_body] = {
    .visible = true,
    .named = true,
  },
  [sym_json_object] = {
    .visible = true,
    .named = true,
  },
  [sym_json_array] = {
    .visible = true,
    .named = true,
  },
  [sym_json_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_json_value] = {
    .visible = true,
    .named = true,
  },
  [sym_urlencoded_body] = {
    .visible = true,
    .named = true,
  },
  [sym_urlencoded_key_val] = {
    .visible = true,
    .named = true,
  },
  [sym_backend] = {
    .visible = true,
    .named = true,
  },
  [sym_backendoptions] = {
    .visible = true,
    .named = true,
  },
  [sym_backendoption] = {
    .visible = true,
    .named = true,
  },
  [sym_config] = {
    .visible = true,
    .named = true,
  },
  [sym_config_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_config_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_headers_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_urlencoded_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_backendoptions_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_config_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 2,
        '#', 142,
        '%', 4,
        ',', 113,
        '-', 69,
        '.', 137,
        ':', 107,
        '=', 91,
        'F', 25,
        'T', 54,
        '[', 82,
        ']', 88,
        'f', 8,
        'n', 22,
        't', 12,
        '{', 111,
        '}', 114,
        'B', 26,
        'b', 26,
        'C', 48,
        'c', 48,
        'H', 35,
        'h', 35,
        'M', 33,
        'm', 33,
        'Q', 62,
        'q', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(130);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(117);
      if (lookahead == '\\') ADVANCE(73);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(141);
      if (lookahead == '[') ADVANCE(83);
      if (lookahead == '{') ADVANCE(112);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(72);
      END_STATE();
    case 4:
      if (lookahead == '2') ADVANCE(6);
      if (lookahead == '3') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '2') ADVANCE(7);
      if (lookahead == '6') ADVANCE(123);
      if (lookahead != 0) ADVANCE(123);
      END_STATE();
    case 6:
      if (lookahead == '6') ADVANCE(125);
      END_STATE();
    case 7:
      if (lookahead == '6') ADVANCE(125);
      if (lookahead != 0) ADVANCE(123);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(44);
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'D') ADVANCE(124);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(139);
      if (lookahead == 'e') ADVANCE(139);
      END_STATE();
    case 11:
      if (lookahead == 'L') ADVANCE(58);
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'R') ADVANCE(63);
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'S') ADVANCE(34);
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'U') ADVANCE(34);
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(115);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(116);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 24:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 25:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 26:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(28);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(66);
      END_STATE();
    case 29:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(64);
      END_STATE();
    case 30:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(109);
      END_STATE();
    case 31:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(126);
      END_STATE();
    case 32:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 33:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 34:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(139);
      END_STATE();
    case 35:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 36:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 38:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 39:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(42);
      END_STATE();
    case 40:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(131);
      END_STATE();
    case 41:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(49);
      END_STATE();
    case 42:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 43:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 44:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 45:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 46:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 47:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 48:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 49:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 50:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 51:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(61);
      END_STATE();
    case 52:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 53:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 54:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 55:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(106);
      END_STATE();
    case 56:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(127);
      END_STATE();
    case 57:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(60);
      END_STATE();
    case 58:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(34);
      END_STATE();
    case 59:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 60:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(89);
      END_STATE();
    case 61:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(43);
      END_STATE();
    case 62:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 63:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 64:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(110);
      END_STATE();
    case 65:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(90);
      END_STATE();
    case 66:
      if (lookahead == 'K' ||
          lookahead == 'k' ||
          lookahead == 0x212a) ADVANCE(37);
      END_STATE();
    case 67:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(72);
      END_STATE();
    case 68:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(72);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 71:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 72:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 73:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 74:
      if (eof) ADVANCE(81);
      if (lookahead == '\n') SKIP(74);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '[') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(128);
      if (lookahead != 0) ADVANCE(130);
      END_STATE();
    case 75:
      if (eof) ADVANCE(81);
      if (lookahead == '\n') SKIP(75);
      if (lookahead == '#') ADVANCE(140);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '[') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(122);
      if (lookahead != 0) ADVANCE(123);
      END_STATE();
    case 76:
      if (eof) ADVANCE(81);
      if (lookahead == '\n') SKIP(76);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '[') ADVANCE(87);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(133);
      if (lookahead != 0) ADVANCE(134);
      END_STATE();
    case 77:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 2,
        '#', 142,
        ',', 113,
        '-', 69,
        '[', 82,
        ']', 88,
        'f', 15,
        'n', 22,
        't', 20,
        '{', 111,
        '}', 114,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(77);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 78:
      if (eof) ADVANCE(81);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead == '[') ADVANCE(82);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(78);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(138);
      END_STATE();
    case 79:
      if (eof) ADVANCE(81);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '[') ADVANCE(82);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(132);
      END_STATE();
    case 80:
      if (eof) ADVANCE(81);
      if (lookahead == '#') ADVANCE(141);
      if (lookahead == '[') ADVANCE(83);
      if (lookahead == '{') ADVANCE(112);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(72);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(130);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '%') ADVANCE(123);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_host_key);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_querys_key);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == ' ') ADVANCE(108);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '[') ADVANCE(86);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(92);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(102);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '.') ADVANCE(137);
      if (lookahead == '[') ADVANCE(86);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(95);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(98);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      if (('-' <= lookahead && lookahead <= '/') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(102);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '[') ADVANCE(86);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(102);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(97);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(139);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(99);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(100);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(96);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(96);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (eof) ADVANCE(81);
      if (lookahead == ' ') ADVANCE(108);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '[') ADVANCE(86);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(92);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(102);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (eof) ADVANCE(81);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '.') ADVANCE(137);
      if (lookahead == '[') ADVANCE(86);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(95);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(98);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      if (('-' <= lookahead && lookahead <= '/') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(102);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_query_any_token1);
      if (eof) ADVANCE(81);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '[') ADVANCE(86);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(102);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_headers_key);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(108);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(92);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_method_key);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_body_key);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_json_bool);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_json_null);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_json_string);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_json_number);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_json_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_json_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_urlencoded_key);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_urlencoded_val);
      if (lookahead == '#') ADVANCE(140);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '[') ADVANCE(85);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(122);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(123);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_urlencoded_val);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '%') ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_urlencoded_equals);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_urlencoded_amper);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_backend_key);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_backendoptions_key);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_backendoption_token1);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '[') ADVANCE(84);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(128);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(130);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_backendoption_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#') ADVANCE(130);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_backendoption_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(130);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_config_key);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_config_param);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_value);
      if (lookahead == '#') ADVANCE(142);
      if (lookahead == '[') ADVANCE(87);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(133);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(134);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(138);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_bool);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '%') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(140);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(142);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(142);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 77},
  [5] = {.lex_state = 77},
  [6] = {.lex_state = 77},
  [7] = {.lex_state = 77},
  [8] = {.lex_state = 77},
  [9] = {.lex_state = 77},
  [10] = {.lex_state = 77},
  [11] = {.lex_state = 77},
  [12] = {.lex_state = 77},
  [13] = {.lex_state = 77},
  [14] = {.lex_state = 77},
  [15] = {.lex_state = 77},
  [16] = {.lex_state = 77},
  [17] = {.lex_state = 77},
  [18] = {.lex_state = 77},
  [19] = {.lex_state = 77},
  [20] = {.lex_state = 77},
  [21] = {.lex_state = 77},
  [22] = {.lex_state = 77},
  [23] = {.lex_state = 77},
  [24] = {.lex_state = 77},
  [25] = {.lex_state = 80},
  [26] = {.lex_state = 77},
  [27] = {.lex_state = 77},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 104},
  [30] = {.lex_state = 77},
  [31] = {.lex_state = 78},
  [32] = {.lex_state = 78},
  [33] = {.lex_state = 78},
  [34] = {.lex_state = 78},
  [35] = {.lex_state = 78},
  [36] = {.lex_state = 78},
  [37] = {.lex_state = 103},
  [38] = {.lex_state = 74},
  [39] = {.lex_state = 105},
  [40] = {.lex_state = 78},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 74},
  [43] = {.lex_state = 79},
  [44] = {.lex_state = 79},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 74},
  [47] = {.lex_state = 79},
  [48] = {.lex_state = 75},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 78},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 78},
  [60] = {.lex_state = 76},
  [61] = {.lex_state = 78},
  [62] = {.lex_state = 78},
  [63] = {.lex_state = 78},
  [64] = {.lex_state = 78},
  [65] = {.lex_state = 76},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 79},
  [70] = {.lex_state = 79},
  [71] = {.lex_state = 78},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 76},
  [74] = {.lex_state = 74},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 68},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_host_key] = ACTIONS(1),
    [sym_querys_key] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_headers_key] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_method_key] = ACTIONS(1),
    [sym_body_key] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_json_bool] = ACTIONS(1),
    [sym_json_null] = ACTIONS(1),
    [sym_json_string] = ACTIONS(1),
    [sym_json_number] = ACTIONS(1),
    [sym_urlencoded_equals] = ACTIONS(1),
    [sym_urlencoded_amper] = ACTIONS(1),
    [sym_backend_key] = ACTIONS(1),
    [sym_backendoptions_key] = ACTIONS(1),
    [sym_config_key] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_bool] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(90),
    [sym_section] = STATE(3),
    [sym_host] = STATE(76),
    [sym_query] = STATE(76),
    [sym_headers] = STATE(76),
    [sym_method] = STATE(76),
    [sym_body] = STATE(76),
    [sym_backend] = STATE(76),
    [sym_backendoptions] = STATE(76),
    [sym_config] = STATE(76),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(14), 1,
      sym_comment,
    STATE(2), 2,
      sym_section,
      aux_sym_program_repeat1,
    STATE(76), 8,
      sym_host,
      sym_query,
      sym_headers,
      sym_method,
      sym_body,
      sym_backend,
      sym_backendoptions,
      sym_config,
  [24] = 5,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_comment,
    STATE(2), 2,
      sym_section,
      aux_sym_program_repeat1,
    STATE(76), 8,
      sym_host,
      sym_query,
      sym_headers,
      sym_method,
      sym_body,
      sym_backend,
      sym_backendoptions,
      sym_config,
  [48] = 9,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(31), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_json_array_repeat1,
    STATE(27), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [80] = 9,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    STATE(9), 1,
      aux_sym_json_array_repeat1,
    STATE(27), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [112] = 8,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(9), 1,
      aux_sym_json_array_repeat1,
    STATE(27), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [141] = 8,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(10), 1,
      aux_sym_json_array_repeat1,
    STATE(27), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [170] = 8,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    STATE(11), 1,
      aux_sym_json_array_repeat1,
    STATE(27), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [199] = 8,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    STATE(10), 1,
      aux_sym_json_array_repeat1,
    STATE(27), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [228] = 8,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      anon_sym_RBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_json_array_repeat1,
    STATE(27), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(47), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [257] = 8,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    STATE(10), 1,
      aux_sym_json_array_repeat1,
    STATE(27), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [286] = 1,
    ACTIONS(55), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [300] = 1,
    ACTIONS(57), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [314] = 1,
    ACTIONS(59), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [328] = 7,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_RBRACK,
    ACTIONS(63), 1,
      sym_comment,
    STATE(4), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [354] = 1,
    ACTIONS(65), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [368] = 1,
    ACTIONS(67), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [382] = 1,
    ACTIONS(69), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [396] = 1,
    ACTIONS(71), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [410] = 1,
    ACTIONS(73), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [424] = 1,
    ACTIONS(75), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [438] = 1,
    ACTIONS(77), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [452] = 1,
    ACTIONS(79), 10,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [465] = 6,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    STATE(5), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [488] = 8,
    ACTIONS(83), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(88), 1,
      sym_urlencoded_key,
    STATE(57), 1,
      sym_urlencoded_key_val,
    STATE(80), 1,
      sym_json_object,
    STATE(82), 1,
      sym_json_array,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym_comment,
    STATE(77), 2,
      sym_json_body,
      sym_urlencoded_body,
  [515] = 5,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_json_value,
    STATE(23), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(29), 4,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
  [535] = 2,
    ACTIONS(92), 1,
      anon_sym_COMMA,
    ACTIONS(90), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [549] = 8,
    ACTIONS(94), 1,
      sym_host_key,
    ACTIONS(96), 1,
      sym_querys_key,
    ACTIONS(98), 1,
      sym_headers_key,
    ACTIONS(100), 1,
      sym_method_key,
    ACTIONS(102), 1,
      sym_body_key,
    ACTIONS(104), 1,
      sym_backend_key,
    ACTIONS(106), 1,
      sym_backendoptions_key,
    ACTIONS(108), 1,
      sym_config_key,
  [574] = 5,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      aux_sym_query_any_token1,
    STATE(62), 1,
      sym_query_any,
    ACTIONS(116), 2,
      sym_number,
      sym_bool,
    ACTIONS(112), 3,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [593] = 1,
    ACTIONS(42), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_json_bool,
      sym_json_null,
      sym_json_string,
      sym_json_number,
      sym_comment,
  [604] = 5,
    ACTIONS(120), 1,
      sym_identifier,
    ACTIONS(122), 1,
      sym_comment,
    STATE(40), 1,
      sym_query_key,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(33), 2,
      sym_query_key_val,
      aux_sym_query_repeat1,
  [622] = 5,
    ACTIONS(127), 1,
      sym_identifier,
    ACTIONS(130), 1,
      sym_comment,
    STATE(91), 1,
      sym_header_key,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(32), 2,
      sym_header_key_val,
      aux_sym_headers_repeat1,
  [640] = 5,
    ACTIONS(120), 1,
      sym_identifier,
    ACTIONS(135), 1,
      sym_comment,
    STATE(40), 1,
      sym_query_key,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(36), 2,
      sym_query_key_val,
      aux_sym_query_repeat1,
  [658] = 5,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(142), 1,
      sym_comment,
    STATE(91), 1,
      sym_header_key,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(32), 2,
      sym_header_key_val,
      aux_sym_headers_repeat1,
  [676] = 5,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(147), 1,
      sym_comment,
    STATE(91), 1,
      sym_header_key,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(34), 2,
      sym_header_key_val,
      aux_sym_headers_repeat1,
  [694] = 5,
    ACTIONS(152), 1,
      sym_identifier,
    ACTIONS(155), 1,
      sym_comment,
    STATE(40), 1,
      sym_query_key,
    ACTIONS(150), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(36), 2,
      sym_query_key_val,
      aux_sym_query_repeat1,
  [712] = 5,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(162), 1,
      aux_sym_query_any_token1,
    ACTIONS(164), 1,
      anon_sym_SPACE,
    STATE(63), 1,
      sym_header_val,
    ACTIONS(160), 3,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [730] = 5,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    ACTIONS(168), 1,
      anon_sym_LBRACK,
    ACTIONS(170), 1,
      aux_sym_backendoption_token1,
    ACTIONS(172), 1,
      sym_comment,
    STATE(46), 2,
      sym_backendoption,
      aux_sym_backendoptions_repeat1,
  [747] = 4,
    ACTIONS(162), 1,
      aux_sym_query_any_token1,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    STATE(71), 1,
      sym_header_val,
    ACTIONS(177), 3,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [762] = 3,
    ACTIONS(181), 1,
      anon_sym_EQ,
    STATE(64), 1,
      sym_query_val,
    ACTIONS(179), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [775] = 6,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    ACTIONS(187), 1,
      sym_json_string,
    ACTIONS(189), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_json_object_repeat1,
    STATE(66), 1,
      sym_json_pair,
  [794] = 5,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
    ACTIONS(193), 1,
      anon_sym_LBRACK,
    ACTIONS(195), 1,
      aux_sym_backendoption_token1,
    ACTIONS(198), 1,
      sym_comment,
    STATE(42), 2,
      sym_backendoption,
      aux_sym_backendoptions_repeat1,
  [811] = 4,
    ACTIONS(203), 1,
      sym_config_param,
    ACTIONS(205), 1,
      sym_comment,
    ACTIONS(201), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(47), 2,
      sym_config_setting,
      aux_sym_config_repeat1,
  [826] = 4,
    ACTIONS(210), 1,
      sym_config_param,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(208), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(44), 2,
      sym_config_setting,
      aux_sym_config_repeat1,
  [841] = 6,
    ACTIONS(187), 1,
      sym_json_string,
    ACTIONS(189), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_json_object_repeat1,
    STATE(66), 1,
      sym_json_pair,
  [860] = 5,
    ACTIONS(170), 1,
      aux_sym_backendoption_token1,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
    ACTIONS(222), 1,
      anon_sym_LBRACK,
    ACTIONS(224), 1,
      sym_comment,
    STATE(42), 2,
      sym_backendoption,
      aux_sym_backendoptions_repeat1,
  [877] = 4,
    ACTIONS(203), 1,
      sym_config_param,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(227), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(44), 2,
      sym_config_setting,
      aux_sym_config_repeat1,
  [892] = 3,
    ACTIONS(232), 1,
      ts_builtin_sym_end,
    ACTIONS(236), 1,
      sym_urlencoded_val,
    ACTIONS(234), 3,
      anon_sym_LBRACK,
      sym_urlencoded_amper,
      sym_comment,
  [904] = 3,
    ACTIONS(240), 1,
      sym_urlencoded_amper,
    STATE(56), 1,
      aux_sym_urlencoded_body_repeat1,
    ACTIONS(238), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [916] = 1,
    ACTIONS(242), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_EQ,
      sym_identifier,
      sym_comment,
  [924] = 5,
    ACTIONS(187), 1,
      sym_json_string,
    ACTIONS(189), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_json_object_repeat1,
    STATE(66), 1,
      sym_json_pair,
  [940] = 5,
    ACTIONS(187), 1,
      sym_json_string,
    ACTIONS(189), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_json_object_repeat1,
    STATE(66), 1,
      sym_json_pair,
  [956] = 5,
    ACTIONS(187), 1,
      sym_json_string,
    ACTIONS(189), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_json_object_repeat1,
    STATE(66), 1,
      sym_json_pair,
  [972] = 5,
    ACTIONS(187), 1,
      sym_json_string,
    ACTIONS(189), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_json_object_repeat1,
    STATE(66), 1,
      sym_json_pair,
  [988] = 5,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    ACTIONS(248), 1,
      sym_json_string,
    ACTIONS(251), 1,
      sym_comment,
    STATE(55), 1,
      aux_sym_json_object_repeat1,
    STATE(66), 1,
      sym_json_pair,
  [1004] = 3,
    ACTIONS(256), 1,
      sym_urlencoded_amper,
    STATE(56), 1,
      aux_sym_urlencoded_body_repeat1,
    ACTIONS(254), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [1016] = 3,
    ACTIONS(240), 1,
      sym_urlencoded_amper,
    STATE(49), 1,
      aux_sym_urlencoded_body_repeat1,
    ACTIONS(259), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [1028] = 5,
    ACTIONS(187), 1,
      sym_json_string,
    ACTIONS(189), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_json_object_repeat1,
    STATE(66), 1,
      sym_json_pair,
  [1044] = 1,
    ACTIONS(263), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [1051] = 4,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
    ACTIONS(267), 1,
      anon_sym_LBRACK,
    ACTIONS(269), 1,
      sym_value,
    ACTIONS(271), 1,
      sym_comment,
  [1064] = 1,
    ACTIONS(274), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [1071] = 1,
    ACTIONS(276), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [1078] = 1,
    ACTIONS(175), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [1085] = 1,
    ACTIONS(278), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [1092] = 4,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
    ACTIONS(282), 1,
      anon_sym_LBRACK,
    ACTIONS(284), 1,
      sym_value,
    ACTIONS(286), 1,
      sym_comment,
  [1105] = 2,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(291), 3,
      anon_sym_RBRACE,
      sym_json_string,
      sym_comment,
  [1114] = 1,
    ACTIONS(293), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_urlencoded_amper,
      sym_comment,
  [1121] = 1,
    ACTIONS(254), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_urlencoded_amper,
      sym_comment,
  [1128] = 1,
    ACTIONS(295), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_config_param,
      sym_comment,
  [1135] = 1,
    ACTIONS(297), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_config_param,
      sym_comment,
  [1142] = 1,
    ACTIONS(299), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [1149] = 1,
    ACTIONS(301), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_json_string,
      sym_comment,
  [1156] = 4,
    ACTIONS(303), 1,
      ts_builtin_sym_end,
    ACTIONS(305), 1,
      anon_sym_LBRACK,
    ACTIONS(307), 1,
      sym_value,
    ACTIONS(309), 1,
      sym_comment,
  [1169] = 2,
    ACTIONS(312), 1,
      ts_builtin_sym_end,
    ACTIONS(314), 3,
      anon_sym_LBRACK,
      aux_sym_backendoption_token1,
      sym_comment,
  [1178] = 4,
    ACTIONS(187), 1,
      sym_json_string,
    ACTIONS(316), 1,
      anon_sym_RBRACE,
    ACTIONS(318), 1,
      sym_comment,
    STATE(41), 1,
      sym_json_pair,
  [1191] = 1,
    ACTIONS(320), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [1197] = 1,
    ACTIONS(322), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [1203] = 3,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    ACTIONS(187), 1,
      sym_json_string,
    STATE(45), 1,
      sym_json_pair,
  [1213] = 1,
    ACTIONS(324), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [1219] = 1,
    ACTIONS(326), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [1225] = 1,
    ACTIONS(328), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [1231] = 1,
    ACTIONS(326), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [1237] = 1,
    ACTIONS(246), 3,
      anon_sym_RBRACE,
      sym_json_string,
      sym_comment,
  [1243] = 1,
    ACTIONS(330), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
  [1249] = 2,
    ACTIONS(332), 1,
      aux_sym_backendoption_token1,
    STATE(70), 1,
      sym_config_value,
  [1256] = 2,
    ACTIONS(334), 1,
      sym_urlencoded_key,
    STATE(68), 1,
      sym_urlencoded_key_val,
  [1263] = 1,
    ACTIONS(336), 1,
      anon_sym_COLON,
  [1267] = 1,
    ACTIONS(338), 1,
      anon_sym_RBRACK,
  [1271] = 1,
    ACTIONS(340), 1,
      anon_sym_RBRACK,
  [1275] = 1,
    ACTIONS(342), 1,
      ts_builtin_sym_end,
  [1279] = 1,
    ACTIONS(344), 1,
      anon_sym_COLON,
  [1283] = 1,
    ACTIONS(346), 1,
      anon_sym_RBRACK,
  [1287] = 1,
    ACTIONS(348), 1,
      anon_sym_EQ,
  [1291] = 1,
    ACTIONS(350), 1,
      sym_urlencoded_equals,
  [1295] = 1,
    ACTIONS(352), 1,
      anon_sym_RBRACK,
  [1299] = 1,
    ACTIONS(354), 1,
      anon_sym_RBRACK,
  [1303] = 1,
    ACTIONS(356), 1,
      anon_sym_COLON,
  [1307] = 1,
    ACTIONS(358), 1,
      anon_sym_RBRACK,
  [1311] = 1,
    ACTIONS(360), 1,
      anon_sym_RBRACK,
  [1315] = 1,
    ACTIONS(362), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 80,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 141,
  [SMALL_STATE(8)] = 170,
  [SMALL_STATE(9)] = 199,
  [SMALL_STATE(10)] = 228,
  [SMALL_STATE(11)] = 257,
  [SMALL_STATE(12)] = 286,
  [SMALL_STATE(13)] = 300,
  [SMALL_STATE(14)] = 314,
  [SMALL_STATE(15)] = 328,
  [SMALL_STATE(16)] = 354,
  [SMALL_STATE(17)] = 368,
  [SMALL_STATE(18)] = 382,
  [SMALL_STATE(19)] = 396,
  [SMALL_STATE(20)] = 410,
  [SMALL_STATE(21)] = 424,
  [SMALL_STATE(22)] = 438,
  [SMALL_STATE(23)] = 452,
  [SMALL_STATE(24)] = 465,
  [SMALL_STATE(25)] = 488,
  [SMALL_STATE(26)] = 515,
  [SMALL_STATE(27)] = 535,
  [SMALL_STATE(28)] = 549,
  [SMALL_STATE(29)] = 574,
  [SMALL_STATE(30)] = 593,
  [SMALL_STATE(31)] = 604,
  [SMALL_STATE(32)] = 622,
  [SMALL_STATE(33)] = 640,
  [SMALL_STATE(34)] = 658,
  [SMALL_STATE(35)] = 676,
  [SMALL_STATE(36)] = 694,
  [SMALL_STATE(37)] = 712,
  [SMALL_STATE(38)] = 730,
  [SMALL_STATE(39)] = 747,
  [SMALL_STATE(40)] = 762,
  [SMALL_STATE(41)] = 775,
  [SMALL_STATE(42)] = 794,
  [SMALL_STATE(43)] = 811,
  [SMALL_STATE(44)] = 826,
  [SMALL_STATE(45)] = 841,
  [SMALL_STATE(46)] = 860,
  [SMALL_STATE(47)] = 877,
  [SMALL_STATE(48)] = 892,
  [SMALL_STATE(49)] = 904,
  [SMALL_STATE(50)] = 916,
  [SMALL_STATE(51)] = 924,
  [SMALL_STATE(52)] = 940,
  [SMALL_STATE(53)] = 956,
  [SMALL_STATE(54)] = 972,
  [SMALL_STATE(55)] = 988,
  [SMALL_STATE(56)] = 1004,
  [SMALL_STATE(57)] = 1016,
  [SMALL_STATE(58)] = 1028,
  [SMALL_STATE(59)] = 1044,
  [SMALL_STATE(60)] = 1051,
  [SMALL_STATE(61)] = 1064,
  [SMALL_STATE(62)] = 1071,
  [SMALL_STATE(63)] = 1078,
  [SMALL_STATE(64)] = 1085,
  [SMALL_STATE(65)] = 1092,
  [SMALL_STATE(66)] = 1105,
  [SMALL_STATE(67)] = 1114,
  [SMALL_STATE(68)] = 1121,
  [SMALL_STATE(69)] = 1128,
  [SMALL_STATE(70)] = 1135,
  [SMALL_STATE(71)] = 1142,
  [SMALL_STATE(72)] = 1149,
  [SMALL_STATE(73)] = 1156,
  [SMALL_STATE(74)] = 1169,
  [SMALL_STATE(75)] = 1178,
  [SMALL_STATE(76)] = 1191,
  [SMALL_STATE(77)] = 1197,
  [SMALL_STATE(78)] = 1203,
  [SMALL_STATE(79)] = 1213,
  [SMALL_STATE(80)] = 1219,
  [SMALL_STATE(81)] = 1225,
  [SMALL_STATE(82)] = 1231,
  [SMALL_STATE(83)] = 1237,
  [SMALL_STATE(84)] = 1243,
  [SMALL_STATE(85)] = 1249,
  [SMALL_STATE(86)] = 1256,
  [SMALL_STATE(87)] = 1263,
  [SMALL_STATE(88)] = 1267,
  [SMALL_STATE(89)] = 1271,
  [SMALL_STATE(90)] = 1275,
  [SMALL_STATE(91)] = 1279,
  [SMALL_STATE(92)] = 1283,
  [SMALL_STATE(93)] = 1287,
  [SMALL_STATE(94)] = 1291,
  [SMALL_STATE(95)] = 1295,
  [SMALL_STATE(96)] = 1299,
  [SMALL_STATE(97)] = 1303,
  [SMALL_STATE(98)] = 1307,
  [SMALL_STATE(99)] = 1311,
  [SMALL_STATE(100)] = 1315,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 6, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 6, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_value, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_body, 3, 0, 0), SHIFT(15),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_val, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query_val, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_query, 3, 0, 0), SHIFT(33),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_headers_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_headers_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_headers_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 4, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_query, 4, 0, 0), SHIFT(36),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headers, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_headers, 4, 0, 0), SHIFT(32),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headers, 3, 0, 0),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_headers, 3, 0, 0), SHIFT(34),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_key_val, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_key_val, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backendoptions, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backendoptions, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [172] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_backendoptions, 3, 0, 0), SHIFT(46),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_key_val, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_key_val, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_key_val, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_backendoptions_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_backendoptions_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_backendoptions_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [198] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_backendoptions_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_config, 3, 0, 0), SHIFT(47),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backendoptions, 4, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backendoptions, 4, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_backendoptions, 4, 0, 0), SHIFT(42),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 4, 0, 0),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_config, 4, 0, 0), SHIFT(44),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_urlencoded_key_val, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_urlencoded_key_val, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_urlencoded_body, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_key, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 2, 0, 0),
  [248] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_urlencoded_body_repeat1, 2, 0, 0),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_urlencoded_body_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_urlencoded_body, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_val, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_host, 3, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_host, 3, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [271] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_host, 3, 0, 0), SHIFT(79),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_any, 1, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_val, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_key_val, 2, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backend, 3, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backend, 3, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [286] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_backend, 3, 0, 0), SHIFT(84),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 1, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_urlencoded_key_val, 3, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_value, 1, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_setting, 3, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_key_val, 4, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_pair, 3, 0, 0),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 3, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method, 3, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [309] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_method, 3, 0, 0), SHIFT(81),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backendoption, 1, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backendoption, 1, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_host, 4, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_body, 1, 0, 0),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 4, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backend, 4, 0, 0),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_key, 1, 0, 0),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [342] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ain(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ain",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
